### ISSUE TITLE
Access to croissants denied 🥺

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/openml-croissant#18]
Some of our croissants cannot be accessed by the general public. A list of inaccessible croissants can be found here:
https://github.com/mlcommons/croissant/blob/main/health/visualizer/report_openml.ipynb

Here's one example:
https://openml1.win.tue.nl/dataset42980/dataset42980/croissant.json

This might be a permission error or maybe the croissant file doesn't exist.

**Comment by PGijsbers** [comment]
That bucket URL is outdated.  MinIO URLs should be formatted `https://openml1.win.tue.nl/datasets/X/ID/croissant.json` where ID is the dataset ID (left padded with 0s to contain at least 4 digits), and X is `floor(ID/10_000)`. 
For example:  https://openml1.win.tue.nl/datasets/0000/0061/croissant.json

However, it looks like this is also broken. Once I have a stable connection I could check the MinIO server to see if there are any croissant files at all, or if they have not yet been moved over.

**Comment by PGijsbers** [comment]
I edited my comment, does that address the concerns?

**Comment by joaquinvanschoren** [comment]
I think so, I did a PR in mlcommons/croissant
