### ISSUE TITLE
Upgrade to fresher croissants 🧑🏼‍🍳

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/openml-croissant#19]
Nobody likes stale croissants :)

OpenML raises errors with the latest version of croissant. See here:
https://colab.research.google.com/drive/1S9xbME_yQUIzrgDPnjR6byI9QXzNbTS9#scrollTo=QFEqoKEW2nhj

Possibly, the source property still uses sc:distribution, but it should now use cr:field, cr:fileSet or cr:fileObject

See the specs here: https://docs.mlcommons.org/croissant/docs/croissant-spec.html#datasource

**Comment by joaquinvanschoren** [comment]
@josvandervelde Would you be able to look into this, or set us on the right track? We should fix this issue soon :)

**Comment by josvandervelde** [comment]
> @josvandervelde Would you be able to look into this, or set us on the right track? We should fix this issue soon :)

Yes I'll fix it today!

**Comment by josvandervelde** [comment]
Done!

- updated the code https://github.com/openml/openml-croissant/pull/20
- updating the croissant files (still busy, 4000/5684 done)
- updated the croissant-converter on k8s

**Comment by joaquinvanschoren** [comment]
Awesome. Thanks, Jos!
